# Session 28 Data Assessing and Cleaning

In [1]:
import pandas as pd
import numpy as np

## Data Analysis Process (Recap and Context)

The data analysis workflow typically progresses through the following structured stages:

1. Asking Questions
2. Data Wrangling

   * Gathering Data
   * Assessing Data
   * Cleaning Data
3. Exploratory Data Analysis (EDA)
4. Drawing Conclusions
5. Communicating Results

In the previous session, the focus was on **Data Gathering**. This session shifts attention to the next critical stages within data wrangling: **Data Assessing** and **Data Cleaning**. Upcoming sessions will cover **EDA**, **Drawing Conclusions**, and finally **Communicating Results** through reports, presentations, and dashboards.

---

## Session Overview: Mindset and Approach

A key objective of this session is to develop a structured analytical mindset toward data quality.

* Approach data like an investigator: identify inconsistencies, question anomalies, and validate assumptions.
* Focus on building a **framework for thinking**, rather than memorizing rigid steps.
* Understand that frameworks may vary across projects and organizations, but the underlying principles remain consistent.
* The ultimate goal is to develop intuition for identifying and resolving data issues effectively.

---

## Data Wrangling: Conceptual Breakdown

Data Wrangling consists of three interconnected stages:

1. Data Gathering
2. Data Assessing
3. Data Cleaning

With data already collected, the next step is to **assess its quality and structure** before applying any cleaning techniques.

---

## 1b. Data Assessing

Data assessing involves thoroughly examining the dataset to understand its structure, content, and potential issues. This step is essential before cleaning, as it informs *what* needs to be fixed and *how*.

---

### Types of Unclean Data

Unclean data can broadly be categorized into two types:

---

### 1. Dirty Data (Quality Issues)

Dirty data refers to **content-related problems** that affect the accuracy and reliability of the dataset.

**Common characteristics:**

* Duplicate records
* Missing values
* Corrupted entries
* Inaccurate or inconsistent data

These issues directly impact the correctness of analysis and model performance.

---

### 2. Messy Data (Tidiness Issues)

Messy data refers to **structural problems** that make data difficult to analyze, even if the content itself is correct.

A dataset is considered **tidy** when it satisfies the following principles:

* Each variable forms a column
* Each observation forms a row
* Each observational unit forms a table

---

### Example: Messy vs Tidy Data

**Messy Data Format:**

| Year | China | India | Pakistan |
| ---- | ----- | ----- | -------- |
| 1950 | value | value | value    |
| 1970 | value | value | value    |
| 1980 | value | value | value    |

**Issue:**

* Multiple variables (countries) are stored as columns instead of values in a single column.
* Violates the principle: *Each variable should form a column.*

---

**Tidy Data Format:**

| Year | Country  | Population |
| ---- | -------- | ---------- |
| 1950 | China    | value      |
| 1950 | India    | value      |
| 1950 | Pakistan | value      |

**Why this is better:**

* Each variable (Year, Country, Population) is clearly defined as a column
* Each row represents a single observation
* Enables easier filtering, grouping, and analysis

---

### Key Insight

Data assessing is not about fixing issues—it is about **identifying and understanding them**. A well-assessed dataset makes the cleaning process systematic and efficient.

---

In [2]:
patients = pd.read_csv("data/patients.csv")
treatments = pd.read_csv("data/treatments.csv")
treatments_cut = pd.read_csv("data/treatments_cut.csv")
adverse_reactions = pd.read_csv("data/adverse_reactions.csv")

In [3]:
patients.head()

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
0,1,female,Zoe,Wellish,576 Brown Bear Drive,Rancho California,California,92390.0,United States,951-719-9170ZoeWellish@superrito.com,7/10/1976,121.7,66,19.6
1,2,female,Pamela,Hill,2370 University Hill Road,Armstrong,Illinois,61812.0,United States,PamelaSHill@cuvox.de+1 (217) 569-3204,4/3/1967,118.8,66,19.2
2,3,male,Jae,Debord,1493 Poling Farm Road,York,Nebraska,68467.0,United States,402-363-6804JaeMDebord@gustr.com,2/19/1980,177.8,71,24.8
3,4,male,Liêm,Phan,2335 Webster Street,Woodbridge,NJ,7095.0,United States,PhanBaLiem@jourrapide.com+1 (732) 636-8246,7/26/1951,220.9,70,31.7
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [4]:
treatments.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.97
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32

In [5]:
treatments_cut.head()

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,jožka,resanovič,22u - 30u,-,7.56,7.22,0.34
1,inunnguaq,heilmann,57u - 67u,-,7.85,7.45,NaN
2,alwin,svensson,36u - 39u,-,7.78,7.34,NaN
3,thể,lương,-,61u - 64u,7.64,7.22,0.92
4,amanda,ribeiro,36u - 44u,-,7.85,7.47,0.38

In [6]:
adverse_reactions.head()

  given_name     surname           adverse_reaction
0      berta  napolitani  injection site discomfort
1       lena        baer               hypoglycemia
2     joseph         day               hypoglycemia
3     flavia  fiorentino                      cough
4    manouck     wubbels          throat irritation

## Data Understanding and Contextualization

The first critical step after acquiring a dataset is to **develop a comprehensive understanding of its context, domain, and structure**. Without this, any analysis risks being superficial or misleading.

* If the dataset contains domain-specific or technical terminology, it is essential to **consult subject-matter experts**.
* A strong contextual understanding enables analysts to:

  * Interpret variables correctly
  * Identify inconsistencies
  * Formulate meaningful and relevant questions

---

## 1. Dataset Summary

This dataset represents a **clinical trial involving diabetic patients** aimed at evaluating the effectiveness of an oral insulin drug.

* Total patients: **500**
* Patients enrolled in trial: **350**
* Initial condition:

  * None were using *Novodra* (injectable insulin) or *Auralin* (oral insulin under study) as their primary insulin source
  * All patients exhibited **elevated HbA1c levels**

### Trial Design

1. **Baseline Phase (4 weeks):**

   * All 350 patients were administered *Novodra*
   * Objective: Establish baseline HbA1c levels and insulin dosage

2. **Treatment Phase (24 weeks):**

   * 175 patients switched to *Auralin*
   * 175 patients continued with *Novodra*

3. **Additional Data Collected:**

   * Adverse reactions reported by patients

### Key Consideration

* The initial 4-week period is **insufficient to capture meaningful HbA1c changes**, as HbA1c reflects average blood glucose over approximately 3 months.
* The primary evaluation is based on the **24-week treatment period**.

---

## 2. Column Descriptions

### Table: `patients`

This table contains **demographic and physiological information** for each patient.

* `patient_id`: Unique identifier in the Master Patient Index
* `assigned_sex`: Biological sex assigned at birth (male/female)
* `given_name`, `surname`: Patient’s first and last name
* `address`, `city`, `state`, `zip_code`, `country`: Location details (all patients are from the United States)
* `contact`: Phone number and email
* `birthdate`: Date of birth (eligibility: age ≥ 18)
* `weight`: Weight in pounds (lbs)
* `height`: Height in inches (in)
* `bmi`: Body Mass Index

**Important Constraints:**

* BMI inclusion range: **16 ≤ BMI ≤ 38**
* BMI is derived using height and weight, making it a **computed feature**

---

### Tables: `treatments` and `treatments_cut`

These tables contain **treatment-related clinical data**.

* `given_name`, `surname`: Patient identifiers
* `auralin`:

  * Format: `baseline dose - final dose`
  * Represents median daily insulin dose before and after switching to Auralin
* `novodra`:

  * Same structure as above, but for patients continuing Novodra
* `hba1c_start`: HbA1c level at treatment start (%)
* `hba1c_end`: HbA1c level at treatment end (%)
* `hba1c_change`: Difference between start and end HbA1c

### Clinical Objective

* Auralin must demonstrate **non-inferiority** compared to Novodra
* Defined as:

  * Upper bound of 95% confidence interval < 0.4%
  * Metric: difference in mean HbA1c reduction (Novodra − Auralin)

---

### Data Integrity Observation

* Expected patient records: **350**
* `treatments` table: **280 rows**
* `treatments_cut` table: **70 rows**

**Inference:**

* The dataset appears to be **artificially split into two tables**
* The reason and method of this split are unclear, indicating a potential **data structuring issue (tidiness problem)**

---

### Table: `adverse_reactions`

This table captures **safety-related outcomes**.

* `given_name`, `surname`: Patient identifiers
* `adverse_reaction`: Reported side effect

**Note:**

* Includes patients from both treatment groups (Auralin and Novodra)

---

## 3. Additional Domain Insights

* **Insulin dosage is individualized** due to varying insulin resistance among patients

  * Both baseline and final doses are necessary to compute meaningful changes

* **HbA1c as a metric:**

  * Reflects average blood glucose over ~3 months
  * More reliable than short-term glucose measurements

* **Diversity in Clinical Trials:**

  * Representation across age, sex, race, and ethnicity is essential
  * The `patients` table reflects this diversity, improving the validity and generalizability of results

---

## Key Insight

A well-documented dataset summary and column-level understanding form the foundation of **effective data assessing**. This step ensures that:

* Structural and quality issues can be identified early
* Domain-specific nuances are not overlooked
* Subsequent data cleaning and analysis are both accurate and meaningful

---

## Types of Data Assessment

Data assessment can be broadly categorized into two complementary approaches:

### Manual Assessment

Manual assessment involves **visually inspecting the dataset** using tools such as spreadsheets (e.g., Excel, Google Sheets).

* Analysts scroll through the dataset to identify anomalies, inconsistencies, and patterns
* Particularly effective for spotting:

  * Formatting inconsistencies
  * Obvious outliers
  * Human-readable errors (e.g., typos)

**Industry Insight:**
Despite the availability of advanced tools, experienced analysts often rely heavily on manual inspection to build intuition about the data.

---

### Programmatic Assessment

Programmatic assessment uses **code-based techniques**, typically leveraging libraries such as Pandas.

Common functions include:

* `info()` → Understand structure, data types, and missing values
* `describe()` → Generate statistical summaries
* `sample()` → Randomly inspect subsets of data

This approach is essential for:

* Scaling analysis to large datasets
* Systematically identifying hidden issues
* Validating assumptions discovered during manual assessment

---

## Steps in Data Assessment

Data assessment follows a two-step iterative process:

### 1. Discover (Exploration)

* Explore the dataset using both manual and programmatic methods
* Identify potential issues related to quality and structure

### 2. Document

* Record all identified issues clearly
* Categorize them into:

  * **Dirty Data (quality issues)**
  * **Messy Data (tidiness issues)**

---

## Exporting Data for Manual Assessment

To facilitate manual inspection, datasets can be consolidated into a single Excel workbook:

```python
# export data for manual assessment

with pd.ExcelWriter('clinical_trials.xlsx') as writer:
    patients.to_excel(writer, sheet_name='patients')
    treatments.to_excel(writer, sheet_name='treatments')
    treatments_cut.to_excel(writer, sheet_name='treatments_cut')
    adverse_reactions.to_excel(writer, sheet_name='adverse_reactions')
```

This enables efficient navigation across multiple tables during visual inspection.

---

## Issues Identified: Manual Assessment

### 1. Dirty Data (Quality Issues)

#### Table: `patients`

* Typographical error:

  * `patient_id = 9` → "Dsvid" instead of "David" (validated via email); `accuracy`

* Inconsistent formatting:

  * `state` column contains both full names and abbreviations; `consistency`

* Invalid values:

  * `zip_code` contains 4-digit entries (invalid format); `validity`

* Duplicate records:

  * Six identical entries labeled "John Doe"; `accuracy`
  * `patient_id`: 216, 230, 238, 245, 252, 278
  * Likely placeholder or improperly handled records

---

#### Tables: `treatments` and `treatments_cut`

* Case inconsistency:

  * `given_name` and `surname` in lowercase; `consistency`

* Redundant unit notation:

  * Character `'u'` in `auralin` and `novodra` columns; `validity`
  * Unnecessary since unit is consistent across dataset

* Missing value representation:

  * `'-'` used instead of proper null values (NaN); `validity`

* Missing data:

  * Incomplete entries in `hba1c_change`; `completeness`

---

#### Table: `adverse_reactions`

* Case inconsistency:

  * `given_name` and `surname` in lowercase; `consistency`
  * May cause issues during joins/merges

---

### 2. Messy Data (Tidiness Issues)

#### Table: `patients`

* `contact` column combines:

  * Phone number
  * Email address
* Violates the principle: **each variable should have its own column**

---

#### Table: `treatments`

* Columns `auralin` and `novodra` contain:

  * Two values in a single field (start dose – end dose)
* Should be split into:

  * `start_dose`
  * `end_dose`

---

#### Table: `adverse_reactions`

* Stored as a separate table despite being:

  * An attribute related to patients/treatments
* May need restructuring depending on analysis requirements

---

## Issues Identified: Programmatic Assessment

### Table: `patients`

* Duplicate placeholder records:

  * Multiple "John Doe" entries confirmed using filtering

* Missing values:

  * `address`, `city`, `state`, `zip_code`, `country`, `contact`
  * Missing in 12 observations

* Incorrect data types:

  * `assigned_sex`
  * `zip_code`
  * `birthdate`

* Logical inconsistencies:

  * `patient_id = 211`: weight inconsistent with BMI and height
  * `patient_id = 5`: height inconsistent with BMI and weight

---

### Tables: `treatments` and `treatments_cut`

* Duplicate entry:

  * Patient "Joseph Day"; `accuracy`

* Incorrect value:

  * `hba1c_change` recorded as `0.9` instead of `0.4`; `accuracy`

---

## Key Insight

Data assessment is inherently **iterative**:

* Manual and programmatic methods complement each other
* Issues discovered in one approach often guide deeper exploration in the other
* Proper documentation ensures a **systematic transition to data cleaning**

---

In [ ]:
# export data for manual assessment

with pd.ExcelWriter('clinical_trials.xlsx') as writer:
  patients.to_excel(writer, sheet_name='patients')
  treatments.to_excel(writer, sheet_name='treatments')
  treatments_cut.to_excel(writer, sheet_name='treatments_cut')
  adverse_reactions.to_excel(writer, sheet_name='adverse_reactions')

In [9]:
patients.sample(8)

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
147,148,male,Kristian,Vukelić,4411 Libby Street,West Los Angeles,California,90025.0,United States,310-268-6864KristianVukelic@teleworm.us,11/30/1958,191.4,66,30.9
185,186,male,Brice,Authier,1895 Hart Ridge Road,Elkton,MI,48731.0,United States,BriceAuthier@superrito.com1 989 375 2216,12/16/1939,125.1,64,21.5
298,299,male,Connor,Harold,3688 Glenview Drive,Corpus Christi,TX,78476.0,United States,361-533-5161ConnorHarold@fleckens.hu,9/12/1923,182.2,69,26.9
13,14,female,Anenechi,Chidi,826 Broad Street,Birmingham,AL,35203.0,United States,AnenechiChidi@armyspy.com+1 (205) 417-8095,3/7/1961,228.4,67,35.8
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
203,204,female,Mùi,Lương,1778 Rodney Street,Harvester,MO,63301.0,United States,636-442-6946LuongHongMui@einrot.com,2/29/1956,192.7,60,37.6
429,430,female,Kristiina,Hyypiä,206 Eagle Lane,Grand Forks,MN,58203.0,United States,KristiinaHyypia@cuvox.de218-773-9682,5/2/1922,152.1,65,25.3
46,47,male,Javier,Moquin,1808 Stuart Street,Pittsburgh,PA,15201.0,United States,724-419-3583JavierMoquin@rhyta.com,8/7/1941,163.9,72,22.2

In [3]:
patients[(patients.given_name == 'John') & (patients.surname == "Doe")]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
215,216,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [4]:
patients.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 503 entries, 0 to 502
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   patient_id    503 non-null    int64
 1   assigned_sex  503 non-null    object
 2   given_name    503 non-null    object
 3   surname       503 non-null    object
 4   address       491 non-null    object
 5   city          491 non-null    object
 6   state         491 non-null    object
 7   zip_code      491 non-null    float64
 8   country       491 non-null    object
 9   contact       491 non-null    object
 10  birthdate     503 non-null    object
 11  weight        503 non-null    float64
 12  height        503 non-null    int64
 13  bmi           503 non-null    float64
dtypes: float64(3), int64(2), object(9)
memory usage: 55.1+ KB

In [6]:
patients[patients['address'].isnull()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
209,210,female,Lalita,Eldarkhanov,NaN,NaN,NaN,NaN,NaN,NaN,8/14/1950,143.4,62,26.2
219,220,male,Mỹ,Quynh,NaN,NaN,NaN,NaN,NaN,NaN,4/9/1978,237.8,69,35.1
230,231,female,Elisabeth,Knudsen,NaN,NaN,NaN,NaN,NaN,NaN,9/23/1976,165.9,63,29.4
234,235,female,Martina,Tománková,NaN,NaN,NaN,NaN,NaN,NaN,4/7/1936,199.5,65,33.2
242,243,male,John,O'Brian,NaN,NaN,NaN,NaN,NaN,NaN,2/25/1957,205.3,74,26.4
249,250,male,Benjamin,Mehler,NaN,NaN,NaN,NaN,NaN,NaN,10/30/1951,146.5,69,21.6
257,258,male,Jin,Kung,NaN,NaN,NaN,NaN,NaN,NaN,5/17/1995,231.7,69,34.2
264,265,female,Wafiyyah,Asfour,NaN,NaN,NaN,NaN,NaN,NaN,11/3/1989,158.6,63,28.1
269,270,female,Flavia,Fiorentino,NaN,NaN,NaN,NaN,NaN,NaN,10/9/1937,175.2,61,33.1
278,279,female,Generosa,Cabán,NaN,NaN,NaN,NaN,NaN,NaN,12/16/1962,124.3,69,18.4
286,287,male,Lewis,Webb,NaN,NaN,NaN,NaN,NaN,NaN,4/1/1979,155.3,68,23.6
296,297,female,Chỉ,Lâm,NaN,NaN,NaN,NaN,NaN,NaN,5/14/1990,181.1,63,32.1

In [7]:
treatments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  171 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [8]:
treatments_cut.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  42 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [9]:
adverse_reactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   given_name        34 non-null     object
 1   surname           34 non-null     object
 2   adverse_reaction  34 non-null     object
dtypes: object(3)
memory usage: 948.0+ bytes

In [13]:
patients.duplicated().sum()

np.int64(0)

In [12]:
patients['patient_id'].duplicated().sum()

np.int64(0)

In [16]:
patients.duplicated(subset=['given_name', 'surname']).sum()

np.int64(5)

In [17]:
patients[patients.duplicated(subset=['given_name', 'surname'])]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
229,230,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
237,238,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
244,245,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
251,252,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4
277,278,male,John,Doe,123 Main Street,New York,NY,12345.0,United States,johndoe@email.com1234567890,1/1/1975,180.0,72,24.4

In [18]:
treatments.duplicated().sum()

np.int64(1)

In [19]:
treatments[treatments.duplicated()]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [20]:
treatments[treatments.duplicated(subset=['given_name', 'surname'])]

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
136,joseph,day,29u - 36u,-,7.7,7.19,NaN

In [23]:
treatments_cut[treatments_cut.duplicated()]

Empty DataFrame
Columns: [given_name, surname, auralin, novodra, hba1c_start, hba1c_end, hba1c_change]
Index: []

In [24]:
adverse_reactions.duplicated().sum()

np.int64(0)

In [25]:
patients.describe()

       patient_id      zip_code      weight      height         bmi
count  503.000000    491.000000  503.000000  503.000000  503.000000
mean   252.000000  49084.118126  173.434990   66.634195   27.483897
std    145.347859  30265.807442   33.916741    4.411297    5.276438
min      1.000000   1002.000000   48.800000   27.000000   17.100000
25%    126.500000  21920.500000  149.300000   63.000000   23.300000
50%    252.000000  48057.000000  175.300000   67.000000   27.200000
75%    377.500000  75679.000000  199.500000   70.000000   31.750000
max    503.000000  99701.000000  255.900000   79.000000   37.700000

In [26]:
patients[patients['weight'] == 48.8000000]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
210,211,female,Camilla,Zaitseva,4689 Briarhill Lane,Wooster,OH,44691.0,United States,330-202-2145CamillaZaitseva@superrito.com,11/26/1938,48.8,63,19.1

In [27]:
patients[patients.height == patients.height.min()]

,patient_id,assigned_sex,given_name,surname,address,city,state,zip_code,country,contact,birthdate,weight,height,bmi
4,5,male,Tim,Neudorf,1428 Turkey Pen Lane,Dothan,AL,36303.0,United States,334-515-7487TimNeudorf@cuvox.de,2/18/1928,192.3,27,26.1

In [28]:
treatments.describe()

       hba1c_start   hba1c_end  hba1c_change
count   280.000000  280.000000    171.000000
mean      7.985929    7.589286      0.546023
std       0.568638    0.569672      0.279555
min       7.500000    7.010000      0.200000
25%       7.660000    7.270000      0.340000
50%       7.800000    7.420000      0.380000
75%       7.970000    7.570000      0.920000
max       9.950000    9.580000      0.990000

In [30]:
treatments.sort_values('hba1c_change', na_position='first')

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,NaN
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,NaN
8,saber,ménard,-,54u - 54u,8.08,7.70,NaN
9,asia,woźniak,30u - 36u,-,7.76,7.37,NaN
10,joseph,day,29u - 36u,-,7.70,7.19,NaN
...,...,...,...,...,...,...,...
49,jackson,addison,-,42u - 42u,7.99,7.51,0.98
17,gina,cain,-,36u - 36u,7.88,7.40,0.98
138,giovana,rocha,-,23u - 21u,7.87,7.38,0.99
32,laura,ehrlichmann,-,43u - 40u,7.95,7.46,0.99
245,wu,sung,-,47u - 48u,7.61,7.12,0.99

In [31]:
adverse_reactions.describe()

       given_name  surname adverse_reaction
count          34       34               34
unique         34       33                6
top         berta  johnson     hypoglycemia
freq            1        2               19

In [34]:
adverse_reactions[adverse_reactions['surname'].duplicated()]

   given_name  surname adverse_reaction
10      tegan  johnson         headache

In [38]:
adverse_reactions.query("surname == 'johnson'")

   given_name  surname adverse_reaction
6      louise  johnson     hypoglycemia
10      tegan  johnson         headache

## Data Quality Dimensions

To systematically evaluate data issues, four key quality dimensions are used:

* **Completeness**
  Determines whether required data is missing

* **Validity**
  Ensures data conforms to defined rules and constraints

  * Examples:

    * Negative height
    * Duplicate `patient_id`

* **Accuracy**
  Checks whether data correctly represents real-world values

  * Example:

    * Weight = 1 kg for an adult (possible, but highly unrealistic)

* **Consistency**
  Ensures uniform representation of data across the dataset

  * Example:

    * "New York" vs "NY"

**Key Distinction:**

* *Invalid data* is impossible
* *Inaccurate data* is possible but implausible

---

## Purpose of Labelling Issues

Assigning each issue a **data quality label** helps in:

* Prioritizing fixes
* Understanding the nature of the problem
* Designing an efficient cleaning strategy

> Labelling is applied only to **Dirty Data (quality issues)** and not to **Messy Data (tidiness issues)**.

---

## Order of Severity

The **Order of Severity** defines the relative impact of different data quality issues:

```
Completeness < Validity < Accuracy < Consistency
```

### Interpretation

* **Completeness (Most Severe)**
  Missing data can completely block analysis or introduce bias

* **Validity**
  Invalid data breaks assumptions and may cause system or computation failures

* **Accuracy**
  Inaccurate data leads to misleading insights, even if technically usable

* **Consistency (Least Severe)**
  Primarily affects readability and processing, but is usually easier to fix

**Key Insight:**
This ordering helps prioritize which issues should be addressed first to minimize downstream errors.

---

## Data Cleaning Order

Based on the severity and dependencies between issues, the recommended sequence for cleaning is:

1. **Quality → Completeness**

   * Handle missing values first

2. **Tidiness (Structural Issues)**

   * Reshape and organize data into a proper format

3. **Quality → Validity**

   * Fix invalid entries (e.g., incorrect formats, impossible values)

4. **Quality → Accuracy**

   * Correct logically inconsistent or suspicious values

5. **Quality → Consistency**

   * Standardize formats and representations

### Why This Order Matters

* Cleaning **out of order** can:

  * Introduce new errors
  * Make transformations harder
  * Lead to inefficient workflows

* For example:

  * Fixing consistency before handling missing values may require repeating work
  * Tidiness must come early because structural changes affect how data is processed

---

## Data Cleaning Workflow

A structured approach ensures reproducibility and clarity:

### 1. Define

Clearly state:

* The issue
* The intended solution

**Example:**
Standardize state names using a mapping dictionary

---

### 2. Code

* Implement the solution using appropriate tools (e.g., Pandas)

---

### 3. Test

* Verify that:

  * The issue has been resolved
  * No new issues have been introduced

---

## Best Practice

Before starting any cleaning process:

* **Always create a copy of the dataset**

```python
patients_clean = patients.copy()
```

This ensures:

* Original data remains intact
* Changes are reversible
* Debugging becomes easier

---

## Key Insight

Effective data cleaning is not just about fixing errors—it is about **following a structured, prioritized approach** that minimizes risk and ensures high-quality, analysis-ready data.

---

In [76]:
patients_df = patients.copy()
treatments_df = treatments.copy()
treatments_cut_df = treatments_cut.copy()
adverse_reactions_df = adverse_reactions.copy()

### Define
- replace all missing values of patients_df with "No data"
- subtract `hba1c_start` from `hba1c_end` to get all the `hba1c_change` values.

In [77]:
# code
patients_df = patients_df.fillna("No data")

# test
patients_df.isna().sum()

patient_id      0
assigned_sex    0
given_name      0
surname         0
address         0
city            0
state           0
zip_code        0
country         0
contact         0
birthdate       0
weight          0
height          0
bmi             0
dtype: int64

In [78]:
# code
treatments_df['hba1c_change'] = treatments_df['hba1c_start'] - treatments_df['hba1c_end']
treatments_cut_df['hba1c_change'] = treatments_cut_df['hba1c_start'] - treatments_cut_df['hba1c_end']

In [79]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    280 non-null    object
 1   surname       280 non-null    object
 2   auralin       280 non-null    object
 3   novodra       280 non-null    object
 4   hba1c_start   280 non-null    float64
 5   hba1c_end     280 non-null    float64
 6   hba1c_change  280 non-null    float64
dtypes: float64(3), object(4)
memory usage: 15.4+ KB

In [80]:
treatments_cut_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    70 non-null     object
 1   surname       70 non-null     object
 2   auralin       70 non-null     object
 3   novodra       70 non-null     object
 4   hba1c_start   70 non-null     float64
 5   hba1c_end     70 non-null     float64
 6   hba1c_change  70 non-null     float64
dtypes: float64(3), object(4)
memory usage: 4.0+ KB

In [81]:
treatments_df = pd.concat([treatments_df, treatments_cut_df])
treatments_df

,given_name,surname,auralin,novodra,hba1c_start,hba1c_end,hba1c_change
0,veronika,jindrová,41u - 48u,-,7.63,7.20,0.43
1,elliot,richardson,-,40u - 45u,7.56,7.09,0.47
2,yukitaka,takenaka,-,39u - 36u,7.68,7.25,0.43
3,skye,gormanston,33u - 36u,-,7.97,7.62,0.35
4,alissa,montez,-,33u - 29u,7.78,7.46,0.32
...,...,...,...,...,...,...,...
65,rovzan,kishiev,32u - 37u,-,7.75,7.41,0.34
66,jakob,jakobsen,-,28u - 26u,7.96,7.51,0.45
67,bernd,schneider,48u - 56u,-,7.74,7.44,0.30
68,berta,napolitani,-,42u - 44u,7.68,7.21,0.47
69,armina,sauvé,36u - 46u,-,7.86,7.40,0.46

In [82]:
treatments_df = treatments_df.melt(id_vars=['given_name', 'surname', 'hba1c_start', 'hba1c_end', 'hba1c_change'],
                   var_name='type', value_name='dosage_range')
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
1,elliot,richardson,7.56,7.09,0.47,auralin,-
2,yukitaka,takenaka,7.68,7.25,0.43,auralin,-
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
4,alissa,montez,7.78,7.46,0.32,auralin,-
...,...,...,...,...,...,...,...
695,rovzan,kishiev,7.75,7.41,0.34,novodra,-
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
697,bernd,schneider,7.74,7.44,0.30,novodra,-
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u
699,armina,sauvé,7.86,7.40,0.46,novodra,-

In [83]:
treatments_df = treatments_df[treatments_df['dosage_range'] != '-']
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_range
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u - 48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u - 36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u - 42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u - 38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u - 36u
...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u - 51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u - 23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u - 23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u - 26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u - 44u

In [84]:
treatments_df['dosage_start'] = treatments_df['dosage_range'].str.split('-').str.get(0)
treatments_df['dosage_end'] = treatments_df['dosage_range'].str.split('-').str.get(1)
treatments_df = treatments_df.drop(columns='dosage_range')
treatments_df

/tmp/ipykernel_8270/2450872695.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_start'] = treatments_df['dosage_range'].str.split('-').str.get(0)
/tmp/ipykernel_8270/2450872695.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  treatments_df['dosage_end'] = treatments_df['dosage_range'].str.split('-').str.get(1)

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41u,48u
3,skye,gormanston,7.97,7.62,0.35,auralin,33u,36u
6,sophia,haugen,7.65,7.27,0.38,auralin,37u,42u
7,eddie,archer,7.89,7.55,0.34,auralin,31u,38u
9,asia,woźniak,7.76,7.37,0.39,auralin,30u,36u
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55u,51u
690,maret,sultygov,7.67,7.30,0.37,novodra,26u,23u
694,lixue,hsueh,9.21,8.80,0.41,novodra,22u,23u
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28u,26u
698,berta,napolitani,7.68,7.21,0.47,novodra,42u,44u

In [85]:
treatments_df['dosage_start'] = treatments_df['dosage_start'].str.replace('u', '')
treatments_df['dosage_end'] = treatments_df['dosage_end'].str.replace('u', '')
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36
6,sophia,haugen,7.65,7.27,0.38,auralin,37,42
7,eddie,archer,7.89,7.55,0.34,auralin,31,38
9,asia,woźniak,7.76,7.37,0.39,auralin,30,36
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55,51
690,maret,sultygov,7.67,7.30,0.37,novodra,26,23
694,lixue,hsueh,9.21,8.80,0.41,novodra,22,23
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26
698,berta,napolitani,7.68,7.21,0.47,novodra,42,44

In [86]:
treatments_df['dosage_start'] = treatments_df['dosage_start'].astype('int')
treatments_df['dosage_end'] = treatments_df['dosage_end'].astype('int')

In [87]:
treatments_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 350 entries, 0 to 698
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   given_name    350 non-null    object
 1   surname       350 non-null    object
 2   hba1c_start   350 non-null    float64
 3   hba1c_end     350 non-null    float64
 4   hba1c_change  350 non-null    float64
 5   type          350 non-null    object
 6   dosage_start  350 non-null    int64
 7   dosage_end    350 non-null    int64
dtypes: float64(3), int64(2), object(3)
memory usage: 24.6+ KB

In [88]:
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48
3,skye,gormanston,7.97,7.62,0.35,auralin,33,36
6,sophia,haugen,7.65,7.27,0.38,auralin,37,42
7,eddie,archer,7.89,7.55,0.34,auralin,31,38
9,asia,woźniak,7.76,7.37,0.39,auralin,30,36
...,...,...,...,...,...,...,...,...
688,christopher,woodward,7.51,7.06,0.45,novodra,55,51
690,maret,sultygov,7.67,7.30,0.37,novodra,26,23
694,lixue,hsueh,9.21,8.80,0.41,novodra,22,23
696,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26
698,berta,napolitani,7.68,7.21,0.47,novodra,42,44

In [90]:
treatments_df = treatments_df.merge(adverse_reactions_df, how='left', on=['given_name', 'surname'])
treatments_df

,given_name,surname,hba1c_start,hba1c_end,hba1c_change,type,dosage_start,dosage_end,adverse_reaction
0,veronika,jindrová,7.63,7.20,0.43,auralin,41,48,NaN
1,skye,gormanston,7.97,7.62,0.35,auralin,33,36,NaN
2,sophia,haugen,7.65,7.27,0.38,auralin,37,42,NaN
3,eddie,archer,7.89,7.55,0.34,auralin,31,38,NaN
4,asia,woźniak,7.76,7.37,0.39,auralin,30,36,NaN
...,...,...,...,...,...,...,...,...,...
345,christopher,woodward,7.51,7.06,0.45,novodra,55,51,nausea
346,maret,sultygov,7.67,7.30,0.37,novodra,26,23,NaN
347,lixue,hsueh,9.21,8.80,0.41,novodra,22,23,injection site discomfort
348,jakob,jakobsen,7.96,7.51,0.45,novodra,28,26,hypoglycemia
349,berta,napolitani,7.68,7.21,0.47,novodra,42,44,injection site discomfort

In [96]:
from pathlib import Path

Path("curated_data").mkdir(parents=True, exist_ok=True)

patients_df.to_csv("curated_data/patients_curated.csv", index=False)
treatments_df.to_csv("curated_data/treatments_curated.csv", index=False)
adverse_reactions_df.to_csv("curated_data/adverse_reactions_curated.csv", index=False)